#!/usr/bin/env python3

import re
import time
import os
import matplotlib.pyplot as plt
#from matplotlib import pyplot
#from matplotlib.animation import FuncAnimation
from datetime import datetime
import argparse

LOGFILE = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Bigscreen Beyond Driver\\bin\\log.txt"

# Via Google AI
def follow(targetFile):
    """
    Generator function that tails a file like the 'tail -f' command.
    """
    targetFile.seek(0, os.SEEK_END)
    
    while True:
        line = targetFile.readline()
        if not line:
            time.sleep(1)
            continue
        yield line

def main(args):
    print("Temperature Monitor Started")
    dtFormmat = "%Y-%m-%d %H:%M:%S"
    #figure = pyplot.figure()

    dataSeconds = 0
    if args.lastHours:
        dataSeconds += int(args.lastHours) * 3600
    if args.lastMins:
        dataSeconds += int(args.lastMins) * 60
    if args.lastSecs:
        dataSeconds += int(args.lastSecs)
    print(f"Showing last {dataSeconds} seconds of data.")

    with open(LOGFILE, "r") as lf:
        ti = []
        temps = []
        firstTime = None

        # Iterate over the new lines generated by the follow function
        #for line in follow(lf):
        for line in lf:
            if re.match(r'^\d{4}-\d{2}-\d{2}', line):
                time = line.split(",")[0]
                if firstTime is None:
                    firstTime = datetime.strptime(time, dtFormmat)
                    ti.append(0)
                else:
                    thisTime = datetime.strptime(time, dtFormmat)
                    delta = thisTime - firstTime
                    #print(delta.total_seconds())
                    ti.append(delta.total_seconds())


                temp = line.split(",")[2]
                #print(temp)
                #ti.append(index)
                temps.append(float(temp))
                #index += 1

                #if index == 10:
                #    break

        #plt.plot(ti, temps)
        #plt.scatter(ti, temps)
        plt.xlabel("Seconds")
        plt.ylabel("Temperature")
        plt.title("Temperature over Time")
        #plt.show()

        plt.ion() # turn interactive mode on
        animated_plot = plt.plot(ti, temps, 'bo')[0]

        for line in follow(lf):
            if re.match(r'^\d{4}-\d{2}-\d{2}', line):
                time = line.split(",")[0]
                thisTime = datetime.strptime(time, dtFormmat)
                delta = thisTime - firstTime
                ti.append(delta.total_seconds())
                
                temp = line.split(",")[2]
                temps.append(float(temp))
            
            recentSeconds = ti[-1]
            plotTi = ti
            plotTemps = temps
            if dataSeconds > 0:
                for t in ti:
                    if recentSeconds - t <= dataSeconds:
                        cutIndex = ti.index(t)
                        break
                plotTi = ti[cutIndex:]
                plotTemps = temps[cutIndex:]

            animated_plot.set_xdata(plotTi)
            animated_plot.set_ydata(plotTemps)
            plt.xlim(left = plotTi[0] - 20, right = plotTi[-1] + 100)
            plt.draw()
            plt.pause(5)
        

        

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Monitor BSB temperature from log file.")
    parser.add_argument("--logfile", type=str, default=LOGFILE, help="Path to the log file.")
    parser.add_argument("--lastHours", "-H", type=str, help="Show this many previous hours of data.")
    parser.add_argument("--lastMins", "-M", type=str, help="Show this many previous minutes of data.")
    parser.add_argument("--lastSecs", "-S", type=str, help="Show this many previous seconds of data.")
    args = parser.parse_args()

    LOGFILE = args.logfile

    main(args)